### ISSUE TITLE
Write a good readme

### ISSUE THREAD

**Issue by haacked** [Haack79/todo_pern_stack#1]
A good README will help users get acclimated to your project. https://www.freecodecamp.org/news/how-to-write-a-good-readme-file/

For example, how do I run this locally? You should provide instructions.

Another thing to consider is GitHub's approach to having a `scripts` folder: https://github.com/github/scripts-to-rule-them-all

**Comment by Haack79** [comment]
ooh thank you ! ![selfie-0](https://i.imgur.com/dFoX4Vc.png)
[_GitHub Selfies_](https://github.com/thieman/github-selfies/)
